# Generated by Django 5.0.6 on 2024-08-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departamento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_head_of_area',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
