# Generated by Django 5.0.6 on 2024-08-22 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('Code', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Dimensiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('idMoneda', models.IntegerField(primary_key=True, serialize=False)),
                ('MonedaAbrev', models.CharField(max_length=150)),
                ('CambioSoles', models.FloatField(default=0.0)),
                ('TCDate', models.DateField()),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='OACT',
            fields=[
                ('AcctCode', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('AcctName', models.CharField(max_length=150)),
                ('CurrTotal', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'OACT',
            },
        ),
        migrations.CreateModel(
            name='OCRD',
            fields=[
                ('CardCode', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('CardName', models.CharField(max_length=150)),
                ('CardType', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'OCRD',
            },
        ),
        migrations.CreateModel(
            name='OITM',
            fields=[
                ('ItemCode', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=150)),
                ('PriceUnit', models.FloatField(default=0.0)),
                ('TypeProduct', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'OITM',
            },
        ),
        migrations.CreateModel(
            name='OSTA',
            fields=[
                ('Code', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('Rate', models.FloatField(default=0.0)),
                ('Type', models.IntegerField()),
            ],
            options={
                'verbose_name': 'OSTA',
            },
        ),
        migrations.CreateModel(
            name='OUOM',
            fields=[
                ('Code', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'OUOM',
            },
        ),
        migrations.CreateModel(
            name='OWHS',
            fields=[
                ('WhsCode', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('WhsName', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'OWHS',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('Nombre', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('PrimerNumero', models.IntegerField()),
                ('NumeroSiguiente', models.IntegerField()),
                ('UltimoNumero', models.IntegerField()),
                ('CodigoSerie', models.IntegerField(default=75)),
            ],
            options={
                'verbose_name': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Validaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codValidador', models.CharField(max_length=150)),
                ('codReqUser', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Aprobación',
                'verbose_name_plural': 'Aprobaciones',
            },
        ),
        migrations.CreateModel(
            name='OPRQ',
            fields=[
                ('DocEntry', models.AutoField(primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField()),
                ('Serie', models.IntegerField(null=True)),
                ('ReqCode', models.CharField(max_length=150, verbose_name='ReqCode')),
                ('ReqType', models.IntegerField()),
                ('DocStatus', models.CharField(max_length=10, verbose_name='DocStatus')),
                ('DocType', models.CharField(max_length=10, verbose_name='DocType')),
                ('DocDate', models.DateField(verbose_name='DocDate')),
                ('DocDueDate', models.DateField(verbose_name='DocDueDate')),
                ('ReqDate', models.DateField(null=True, verbose_name='ReqDate')),
                ('SystemDate', models.DateField(null=True, verbose_name='SystemDate')),
                ('Comments', models.CharField(max_length=150)),
                ('Total', models.FloatField(verbose_name='Total')),
                ('TotalImp', models.FloatField(verbose_name='TotalImpuestos')),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.departamento')),
                ('ReqIdUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ReqIdUser')),
                ('moneda', models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.moneda')),
                ('TaxCode', models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.osta')),
            ],
            options={
                'verbose_name': 'OPRQ',
            },
        ),
        migrations.CreateModel(
            name='OWHS_OITM',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('EnStock', models.IntegerField()),
                ('Comprometido', models.IntegerField()),
                ('Pedido', models.IntegerField()),
                ('Disponible', models.IntegerField()),
                ('ItemCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.oitm', verbose_name='ItemCod')),
                ('WhsCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.owhs', verbose_name='WhsCod')),
            ],
            options={
                'verbose_name': 'OWHS',
            },
        ),
        migrations.CreateModel(
            name='PRQ1',
            fields=[
                ('Code', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Quantity', models.IntegerField()),
                ('total', models.FloatField(default=0.0)),
                ('LineStatus', models.CharField(blank=True, default='P', max_length=1, null=True)),
                ('Almacen', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='erp.owhs')),
                ('CuentaMayor', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='erp.oact')),
                ('Currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.moneda')),
                ('ItemCode', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='erp.oitm')),
                ('LineVendor', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='erp.ocrd')),
                ('NumDoc', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='erp.oprq')),
                ('UnidadMedida', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='erp.ouom')),
                ('idDimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.dimensiones')),
            ],
            options={
                'verbose_name': 'PRQ1',
            },
        ),
    ]
