# Generated by Django 5.0.6 on 2024-08-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oitm',
            name='idAlmacen',
            field=models.CharField(blank=True, null=True),
        ),
    ]
