# Generated by Django 5.0.6 on 2024-08-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_oitm_idalmacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='oprq',
            name='DocNumSAP',
            field=models.IntegerField(null=True),
        ),
    ]
