# Generated by Django 5.1.2 on 2024-11-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_oprq_docnumsap'),
    ]

    operations = [
        migrations.AddField(
            model_name='prq1',
            name='Precio',
            field=models.FloatField(default=0.0),
        ),
    ]
