# Generated by Django 5.1.2 on 2025-01-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_prq1_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='DocType',
            field=models.CharField(default='Documento', max_length=10, verbose_name='DocType'),
            preserve_default=False,
        ),
    ]
