# Generated by Django 5.1.2 on 2025-01-13 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_series_doctype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SystemDate', models.DateField(null=True, verbose_name='SystemDate')),
                ('DocDate', models.DateField(verbose_name='DocDate')),
                ('DocDueDate', models.DateField(verbose_name='DocDueDate')),
                ('ReqDate', models.DateField(null=True, verbose_name='RequestDate')),
                ('ItemCode', models.CharField(blank=True, max_length=150, null=True, verbose_name='Código del ítem')),
                ('ItemDescription', models.TextField(verbose_name='Descripción del ítem')),
                ('Quantity', models.IntegerField(verbose_name='Cantidad')),
                ('PrecioUnitario', models.FloatField(verbose_name='Precio unitario')),
                ('Total', models.FloatField(verbose_name='Total')),
                ('Almacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.owhs', verbose_name='Almacén')),
                ('Dimension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.dimensiones', verbose_name='Dimensión')),
                ('Impuesto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.osta', verbose_name='Impuestos')),
                ('Moneda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.moneda', verbose_name='Moneda')),
                ('Orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Detalles', to='erp.orden_compra', verbose_name='Orden asociada')),
                ('Serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.series', verbose_name='Serie')),
                ('Solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
            },
        ),
    ]
