# Generated by Django 5.1.2 on 2025-01-14 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_oprq_tipodoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_compra',
            name='SystemDate',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='SystemDate'),
        ),
    ]
