# Generated by Django 5.1.2 on 2025-01-15 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_remove_orden_compra_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_compra',
            name='NumDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.oprq', verbose_name='Número de Documento'),
        ),
    ]
