# Generated by Django 5.1.2 on 2025-01-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_orden_compra_numdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_compra',
            name='DocNumSAP',
            field=models.IntegerField(null=True),
        ),
    ]
