# Generated by Django 5.1.2 on 2025-01-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_orden_compra_docnumsap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_compra',
            name='DocNumSAP',
        ),
        migrations.AddField(
            model_name='orden_compra',
            name='DocNumSAPoc',
            field=models.IntegerField(null=True, verbose_name='DocNumSAP Orden Compra'),
        ),
    ]
