# Generated by Django 5.1.2 on 2025-01-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_orden_compra_is_processing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_compra',
            name='is_processing',
        ),
    ]
