# Generated by Django 5.1.2 on 2025-01-21 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_remove_orden_compra_is_processing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCC',
            fields=[
                ('DocEntryOC', models.AutoField(primary_key=True, serialize=False)),
                ('DocNumOC', models.IntegerField(unique=True)),
                ('DocTypeOC', models.CharField(default='OC', max_length=10)),
                ('DocDateOC', models.DateField()),
                ('DocDueDateOC', models.DateField()),
                ('SystemDateOC', models.DateField(auto_now_add=True)),
                ('TotalOC', models.FloatField()),
                ('TotalImpuestosOC', models.FloatField()),
                ('CommentsOC', models.TextField(blank=True, null=True)),
                ('DocNumSAPOC', models.IntegerField(null=True, verbose_name='DocNumSAPOC')),
                ('MonedaOC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.moneda')),
                ('ProveedorOC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.ocrd')),
                ('SerieOC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.series')),
                ('SolicitanteOC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('TaxCodeOC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.osta')),
            ],
        ),
        migrations.CreateModel(
            name='OCD1',
            fields=[
                ('CodeOCD', models.AutoField(primary_key=True, serialize=False)),
                ('DescriptionOCD', models.TextField()),
                ('QuantityOCD', models.IntegerField()),
                ('PrecioOCD', models.FloatField()),
                ('TotalOCD', models.FloatField()),
                ('LineStatusOCD', models.CharField(blank=True, default='C', max_length=1, null=True)),
                ('DocNumSAPOCD', models.IntegerField(null=True)),
                ('BaseEntryOCD', models.IntegerField(null=True)),
                ('BaseLineOCD', models.IntegerField(null=True)),
                ('AlmacenOCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.owhs')),
                ('CuentaMayorOCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.oact')),
                ('DimensionOCD', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.dimensiones')),
                ('ItemCodeOCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.oitm')),
                ('LineVendorOCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.ocrd')),
                ('NumDocOCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_oc', to='erp.occ')),
                ('UnidadMedidaOCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.ouom')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Compra',
            },
        ),
    ]
