# Generated by Django 5.1.2 on 2025-01-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_prq1_linecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocd1',
            name='DocEntryOCD',
            field=models.IntegerField(null=True),
        ),
    ]
