# Generated by Django 5.1.2 on 2025-02-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_ocd1_docentryocd'),
    ]

    operations = [
        migrations.AddField(
            model_name='prq1',
            name='LineCount_Indexado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
