# Generated by Django 5.1.2 on 2025-02-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_prq1_linecount_indexado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prq1',
            name='Quantity_rest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prq1',
            name='total_rest',
            field=models.FloatField(default=0.0),
        ),
    ]
