# Generated by Django 5.1.2 on 2025-02-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_prq1_quantity_rest_prq1_total_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prq1',
            name='Quantity_rest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prq1',
            name='total_rest',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
