# Generated by Django 5.1.2 on 2025-02-19 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_alter_prq1_quantity_rest_alter_prq1_total_rest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocd1',
            name='DateAreaGeneralOCD',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocd1',
            name='DateJefePresupuestosOCD',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocd1',
            name='DateLogisticaOCD',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocd1',
            name='idAreaGeneralOCD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idAreaGeneralOCD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ocd1',
            name='idJefePresupuestosOCD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idJefePresupuestosOCD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ocd1',
            name='idLogisticaOCD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idLogisticaOCD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prq1',
            name='DateAreaGeneral',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prq1',
            name='DateJefePresupuestos',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prq1',
            name='DateLogistica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prq1',
            name='idAreaGeneral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idAreaGeneral', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prq1',
            name='idJefePresupuestos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idJefePresupuestos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prq1',
            name='idLogistica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idLogistica', to=settings.AUTH_USER_MODEL),
        ),
    ]
