# Generated by Django 5.1.2 on 2025-02-20 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_ocd1_dateareageneralocd_ocd1_datejefepresupuestosocd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prq1',
            name='LineVendor',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.ocrd'),
        ),
    ]
