# Generated by Django 5.1.2 on 2025-02-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_alter_prq1_linevendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='prq1',
            name='totalimpdet',
            field=models.FloatField(default=0.0, verbose_name='TotalImpuestosDetalle'),
        ),
    ]
