# Generated by Django 5.1.2 on 2025-03-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_remove_moneda_idmoneda_moneda_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prq1',
            name='LineRechazo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
